### ISSUE TITLE
Seems to freeze now and again

### ISSUE THREAD

**Issue by riddle43** [dimok789/homebrew_launcher#6]
Loads fast but seems to freeze on the white Wii U screen about every 3rd launch. Just a heads up so you know but wonderful job please keep up the good work.

5.3.2 FW

**Comment by dimok789** [comment]
The freeze is actually the browser exploit's fault. It happens even before the code of the installer is executed. Usually transfer issues.

Do you host yourself locally in your network? Remote access increases the rate of freeze by a lot. I host everything locally on a raspberry pi on an nginx server (apache works just as well) and it freezes almost never (1 out of 50-100 launches at max).

To reduce the rate of freeze from remote (and locally too of course) the code size needs to be smaller but I cant reduce it for HBL much because it also includes the SD installer.

**Comment by riddle43** [comment]
I'm hosting off my Android but it does seem to go every third time I found
it very strange just wanted to let you know other than that working like a
champ super fast boot and very pleased that you made it thank you

The freeze is actually the browser exploit's fault. It happens even before
the code of the installer is executed. Usually transfer issues.

Do you host yourself locally in your network? Remote access increases the
rate of freeze by a lot. I host everything locally on a raspberry pi on an
nginx server (apache works just as well) and it freezes almost never (1 out
of 50-100 launches at max).

To reduce the rate of freeze from remote (and locally too of course) the
code size needs to be smaller but I cant reduce it for HBL much because it
also includes the SD installer.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/dimok789/homebrew_launcher/issues/6#issuecomment-213920298>

**Comment by dimok789** [comment]
This should be fixed with v1.3. Can you confirm and close the issue if it is done?

**Comment by dimok789** [comment]
Closing it as this should be fixed now.
