### ISSUE TITLE
Starting HBL

### ISSUE THREAD

**Issue by usr577** [dimok789/homebrew_launcher#62]
Where is a site for the browser exploit using a MP4 payload and should I leave the name of the MP4 payload downloaded from release 1.4 or should I rename it to payload.mp4 and where should I put it on my SD?
And is there any newer release because the newest I can find is 5years old?

**Comment by ghost** [comment]
You dont need a newer release because the latest one provided here works on the firmware 5.5.5 perfectly fine. Also the MP4 exploit is incredibly outdated, why are you still trying to use it? The scene has since evolved, and you shouldn't stay behind to avoid incompatability. The current working sites I would suggest https://wiiuexploit.xyz, or the version I host in case one of the others go down https://korozin.github.io

**Comment by Elias02345** [comment]
> You dont need a newer release because the latest one provided here works on the firmware 5.5.5 perfectly fine. Also the MP4 exploit is incredibly outdated, why are you still trying to use it? The scene has since evolved, and you shouldn't stay behind to avoid incompatability. The current working sites I would suggest https://wiiuexploit.xyz, or the version I host in case one of the others go down https://korozin.github.io

I have an wiiu with 5.0.1E how can i use the newest hb launcher without updating the console firmware? the exploit doesnt work on my wiiu. 1.3 only work on it

**Comment by Maschell** [comment]
Most homebrew apps nowadays are designed to only work with 5.5.0 or higher.I would highly recommend updating your console

**Comment by Elias02345** [comment]
i have 5.5.0 or higher. i have 5.5.1 E. i am sorry my memory in my first message was wrong

**Comment by Maschell** [comment]
Then I would still recommend you updating your console to the latest firmware and follow https://wiiu.hacks.guide/#/
